### ISSUE TITLE
Problem when trying to save a draft post

### ISSUE THREAD

**Issue by NotAnyGadgets** [woothemes/theme-customisations#13]
Hi,

When I try to save a draft post, I get the following errors:
# 

Warning: Cannot modify header information - headers already sent by (output started at /home/notany5/public_html/wp-content/plugins/theme-customisations-master/custom/functions.php:36) in /home/notany5/public_html/wp-admin/post.php on line 197
# Warning: Cannot modify header information - headers already sent by (output started at /home/notany5/public_html/wp-content/plugins/theme-customisations-master/custom/functions.php:36) in /home/notany5/public_html/wp-includes/pluggable.php on line 1167

And when I try to add images from the gallery, the images do not show.  I have to deactivate the Theme customisation plugin for everything to work. 

The plugin was working fine but it suddenly happened without updating or changing anything!

Please help.

**Comment by jameskoster** [comment]
> output started at /home/notany5/public_html/wp-content/plugins/theme-customisations-master/custom/functions.php:36

Looks like it's being caused by something you've added. That file is only 17 lines long by default; https://github.com/woothemes/theme-customisations/blob/master/custom/functions.php
