### ISSUE TITLE
Add template file to theme

### ISSUE THREAD

**Issue by dyrobin** [woothemes/theme-customisations#14]
Hi,
It seems that currently this plugin can only override an existed file(like page.php, single.php, etc.) in the theme/childtheme. However, sometimes some template file like image.php or attachment.php does not exist by default but it needs to be added for customization. What do you think of this feature? Is it possible to implement it?

**Comment by jameskoster** [comment]
I checked fairly recently and unfortunately it's not possible at the moment. WordPress core simply doesn't offer any way to enable this functionality in a plugin.
