### ISSUE TITLE
hi james - trouble with install

### ISSUE THREAD

**Issue by miketrikebike** [woothemes/theme-customisations#15]
i uploaded the theme-customisser.php file in my wp-content/plugins directory but when i went to the plugins editor in my wordpress dashboard it wasn't showing up.  just the usual askimet and woocommerce files were there.  was there a .zip file I was supposed to download somewhere.  I'm new to the coding and wordpress world.  i called godaddy (my host) and the tech said that there should maybe be a folder with some other files in it like licensing....etc.

**Comment by jameskoster** [comment]
Hey, visit the [main repository page](https://github.com/woocommerce/theme-customisations) and you can download from there, see;

![download](https://cldup.com/I01kboZfRc.png)

**Comment by miketrikebike** [comment]
Thanks James!
Mike
