### ISSUE TITLE
can't activate 2 copies of this plugin at the same time

### ISSUE THREAD

**Issue by siutz** [woothemes/theme-customisations#16]
Hi can anyone help please?
I have two copies of this plugin.
I have one of these plugins active (with part of my custom css).
I want to activate the second plugin with the rest of my custom css (trying to separate my theme css from my woocommerce css), but I get this fatal error:

Fatal error: Cannot redeclare theme_customisations_main() (previously declared in /home/content/33/8318333/html/wp-content/plugins/GALLERIA-customisations-master/theme-customisations.php:111) in /home/content/33/8318333/html/wp-content/plugins/WOOCOMMERCE-MY-customisations-master/theme-customisations.php on line 112

I'm guessing this is a simple fix? - do I need to change a line or add a word to make these plugins render as different plugins?
Please help. :)

**Comment by jameskoster** [comment]
That error is caused because you're declaring the same function in both of the plugins. Just make sure all your functions names are unique and you should be good :)

**Comment by siutz** [comment]
Hi James thankyou for getting back to me.  Sorry to bother you again but I'm not great with PHP. Can you give me the line to change & what to rename it. I can get into php no worries but need to know what to put there. 
Kind regards 
Garry

**Comment by jameskoster** [comment]
Hey,

If you read the error it actually tells you what line to look at :)
