### ISSUE TITLE
Product images no longer showing when theme customization is activated

### ISSUE THREAD

**Issue by palguire** [woothemes/theme-customisations#19]
As soon as I activate theme-customisations (without any code changes) the product images on the product page no longer show.  I can click where the image should be and they open up.  As soon as I disable the plug-and reload the product page the images appear.

This is my first issue submission so I apologize I didn't include the required information.
My current set up:
Wordpress up-to-date
Woocommerce up-to-date
Storefront up-to-date
using the child theme Boutique

**Comment by jameskoster** [comment]
Hey, probably best to post this in the support forums on WordPress.org. This plugin does _absolutely nothing_ if you've not adjusted it in any way so cannot be responsible for this.

I'd recommend checking other plugins you may have active. WooCommerce 3.0 includes an overhaul of the product gallery. If any other plugins interact with this in any way that will likely be the culprit.

Cheers
