### ISSUE TITLE
Template Hierarchy

### ISSUE THREAD

**Issue by hitrust** [woothemes/theme-customisations#6]
I use this plugin to customize the theme "storefront", which is woocommerce theme.I found it can't support "Template Hierarchy",am I wrong?

**Comment by jameskoster** [comment]
At the moment you can only customise top-level templates IE page.php, single.php etc. It's not possible to customise other templates due to limitations in wp core.

**Comment by BrianBam** [comment]
Wait, so you can't use your own custom templates with this plugin?

**Comment by BrianBam** [comment]
I actually realized that you can't and now I understand what you mean by top-level templates.  It seems like there is a better word for those like WordPress Template files
https://developer.wordpress.org/themes/basics/template-files/ and WordPress template partials
