### ISSUE TITLE
Location of editable files

### ISSUE THREAD

**Issue by BrianBam** [woothemes/theme-customisations#7]
I think that it would be helpful if in your documentation that you were more clear on where to edit these files (i.e style.css).  I did find them inside the plugin, but for a little bit I was wondering where I was supposed to place the files you listed 
- Add any CSS snippets to `custom/style.css`.
- Add any PHP snippets to `custom/functions.php`.
- Add any JS snippets to `custom/custom.js`.
- Add custom top level template files (page.php, single.php etc) to `custom/templates/`.
- Activate the plugin.

Maybe you can just add to this, "these files are located inside the plugin"

Also, I don't see a templates folder inside the custom folder so I'm supposing that we are to create that folder and then add something like page.php inside it?  

Thanks this plugin is helpful and I don't know what I'd do without it when using the theme proshop with storefront.  It's like I'd need a child of a child theme option.

**Comment by jameskoster** [comment]
Glad you like the plugin, I'll update the readme now :)

**Comment by BrianBam** [comment]
Sweet

On Thu, Mar 3, 2016 at 10:55 AM, James Koster notifications@github.com
wrote:

> Closed #7 https://github.com/woothemes/theme-customisations/issues/7
> via 8bfdcee
> https://github.com/woothemes/theme-customisations/commit/8bfdceee33a1b24556f12114dc6be617751d312b
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/woothemes/theme-customisations/issues/7#event-576614496
> .

## 

   Brian Bambl

   (801) 885.2926
   www.Connect4WebDesign.com http://WWW.NUTRITIONFIRSTFITNESS.COM

PRIVILEGE STATEMENT - The information contained in this electronic mail
message is confidential information intended only for the use of the
individual or entity named above, and may be privileged. If the reader of
this message is not the intended recipient, the employee, or the agent
responsible to deliver it to the intended recipient, you are hereby
notified that any dissemination, distribution or copying of this
communication is strictly prohibited. If you have received this
communication in error, please immediately notify us by telephone (801-885
_-2926_), and delete the original message. All information contained in
this communication is the property of the sender. Thank you.
