### ISSUE TITLE
Removing storefront sidebar not working

### ISSUE THREAD

**Issue by abbeyjaye** [woothemes/theme-customisations#8]
Hi There, 
I installed this plugin and added the following code to the custom/functions.php, but it's not working. It works in child themes, so I'm at a stand still with how to figure out why this isn't working. 
`remove_action( 'storefront_sidebar', 'storefront_get_sidebar' );`

Any help is appreciated. Thank you.
~Abbey

**Comment by jameskoster** [comment]
Try this;

```
add_action( 'init', 'jk_remove_sidebar' );
function jk_remove_sidebar() {
remove_action( 'storefront_sidebar', 'storefront_get_sidebar' );
}
```

**Comment by abbeyjaye** [comment]
Thank you.
