### ISSUE TITLE
Modifying style.css and nothing happens?

### ISSUE THREAD

**Issue by Coffetoledo** [woothemes/theme-customisations#9]
Hello, I love this plugin, makes it a lot easier than having a child-theme.

Whenever I modify functions.php it works very well, but nothing happens whenever I edit style.css.

I tried adding this code.

.storefront-primary-navigation{clear:both;background:rgba(0,0,0,.0)!important;margin-left:-99em;margin-right:-99em;padding-left:99em;padding-right:99em
}

Anyone mind helping? I'd love to use style.css but it doesn't want to cooperate with the site.

Thanks.

**Comment by jameskoster** [comment]
Hard to say without seeing a link to your site I'm afraid. The stylesheet is definitely loaded.

**Comment by Coffetoledo** [comment]
And if I send you a link, would you mind helping instead of closing the thread?

Please?

**Comment by Coffetoledo** [comment]
Resolved, I had totally forgot that you need to cache for the changes to show directly.

**Comment by jameskoster** [comment]
Glad this is resolved. I closed the thread as this isn't a code issue. Should have explained, sorry :)
